app/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

from app.views import HomeView


urlpatterns = [
    path('admin/', admin.site.urls),
    
    path('', HomeView.as_view(), name='home'),

    path('tarefas/', include('tarefas.urls')), 

    path('registros/', include('registros.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

registros/urls.py
from django.urls import path
from .views import CriarRegistroTempoView, ListaRegistrosView


urlpatterns = [
    path('', ListaRegistrosView.as_view(), name='lista_registros'),
    path('novo/', CriarRegistroTempoView.as_view(), name='criar_registro'),
]

tarefas/urls.py
from django.urls import path
from .views import CriarTarefaView, ListaTarefasView


urlpatterns = [
    path('', ListaTarefasView.as_view(), name='lista_tarefas'),
    path('nova/', CriarTarefaView.as_view(), name='criar_tarefa'),
]

registros/models.py
from django.db import models
from tarefas.models import Tarefa


class RegistroTempo(models.Model):
    tarefa = models.ForeignKey(Tarefa, on_delete=models.CASCADE, related_name='registros_de_tempo')
    data_registro = models.DateTimeField(auto_now_add=True)
    horas_trabalhadas = models.IntegerField()
    descricao = models.TextField(max_length=500)

    def __str__(self):
        return f"{self.tarefa} - {self.horas_trabalhadas} horas"

tarefas/models.py
from django.db import models
from django.contrib.auth.models import User


class Tarefa(models.Model):
    usuario_responsavel = models.ForeignKey(User, on_delete=models.CASCADE, related_name='tarefas')
    data_criacao = models.DateTimeField(auto_now_add=True)
    descricao = models.TextField(max_length=500)

    def __str__(self):
        return f"{self.usuario_responsavel} - {self.descricao[:20]}"

registros/forms.py
from django import forms
from .models import RegistroTempo


class RegistroTempoForm(forms.ModelForm):
    class Meta:
        model = RegistroTempo
        fields = ['tarefa', 'horas_trabalhadas', 'descricao']

tarefas/forms.py
from django import forms
from tarefas.models import Tarefa


class TarefaModelForm(forms.ModelForm):
    class Meta:
        model = Tarefa
        fields = ['usuario_responsavel', 'descricao']

app/views.py
from django.views.generic import TemplateView


class HomeView(TemplateView):
    template_name = 'home.html'

registros/views.py
from django.contrib import messages
from django.urls import reverse_lazy
from django.db.models import Q
from django.utils.dateparse import parse_date
from django.views.generic import ListView, CreateView

from registros.models import RegistroTempo
from registros.forms import RegistroTempoForm


class ListaRegistrosView(ListView):
    model = RegistroTempo
    template_name = 'registros/lista_registros.html'
    context_object_name = 'registros'
    paginate_by = 10

    def get_queryset(self):
        queryset = super().get_queryset()
        filtros = Q() # Cria uma única expressão de filtro

        usuario = self.request.GET.get('usuario')
        if usuario:            
            filtros &= Q(tarefa__usuario_responsavel__username=usuario)

        tarefa = self.request.GET.get('tarefa')
        if tarefa:
            filtros &= Q(tarefa__descricao__icontains=tarefa)

        data = self.request.GET.get('data')
        if data:
            data_formatada = parse_date(data)
            filtros &= Q(data_registro__date=data_formatada)

        horas_trabalhadas = self.request.GET.get('horas_trabalhadas')
        if horas_trabalhadas and horas_trabalhadas.isdigit():
            filtros &= Q(horas_trabalhadas=horas_trabalhadas)

        return queryset.filter(filtros) # Aplica todos os filtros de uma vez


class CriarRegistroTempoView(CreateView):
    model = RegistroTempo
    form_class = RegistroTempoForm
    template_name = 'registros/criar_registro.html'
    success_url = reverse_lazy('lista_registros')

    def form_valid(self, form):
        messages.success(self.request, 'Registro de tempo adicionado com sucesso!')
        return super().form_valid(form)

tarefas/views.py
from django.contrib import messages
from django.urls import reverse_lazy
from django.views.generic import ListView, CreateView

from tarefas.models import Tarefa
from tarefas.forms import TarefaModelForm


class ListaTarefasView(ListView):
    model = Tarefa
    template_name = 'tarefas/lista_tarefas.html'
    context_object_name = 'tarefas'
    paginate_by = 10


class CriarTarefaView(CreateView):
    model = Tarefa
    form_class = TarefaModelForm
    template_name = 'tarefas/criar_tarefa.html'
    success_url = reverse_lazy('lista_tarefas')

    def form_valid(self, form):
        messages.success(self.request, 'Tarefa criada com sucesso!')
        return super().form_valid(form)

templates/base.html
<!DOCTYPE html>
<html lang="pt-br">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>{% block title %}Controle de Tarefas{% endblock %}</title>

    <!-- Bootstrap CSS and Static -->
    {% load static %}
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <link href="{% static 'css/base.css' %}" rel="stylesheet">
</head>
<body>
    <header class="d-flex justify-content-center py-3 text-bg-dark">
      <ul class="nav nav-pills">
        <li class="nav-item"><a href="{% url 'home' %}" class="nav-link {% if request.path == '/' %}active{% endif %}" aria-current="page">Home</a></li>
        <li class="nav-item"><a href="{% url 'lista_tarefas' %}" class="nav-link {% if request.path == '/tarefas/' %}active{% endif %}">Tarefas</a></li>
        <li class="nav-item"><a href="{% url 'lista_registros' %}" class="nav-link {% if request.path == '/registros/' %}active{% endif %}">Registros</a></li>
      </ul>
    </header>

    {% if messages %}
      <div class="container mt-3">
          {% for message in messages %}
              <div class="alert alert-{{ message.tags }} alert-dismissible fade show" role="alert">
                  {{ message }}
                  <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
              </div>
          {% endfor %}
      </div>
    {% endif %}

    <main class="shadow m-3 rounded p-2">
      {% block content %}{% endblock %}
    </main>
    

    <!-- Bootstrap JS -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>

</body>

<footer class="fixed-bottom text-bg-dark">
  <p class="text-center text-body-primary">© 2024 Kauan Santana</p>
</footer>

</html>

templates/home.html
{% extends 'base.html' %}


{% block content %}
<div class="container text-center">
    <h1>Bem-vindo ao Sistema!</h1>
    <p>Use o menu acima para navegar pelas tarefas e registros.</p>

    <h3 class="m-3 p-2">Descrição</h3>
    <p><b>Tarefas</b>: Listagem e criação de tarefas</p>
    <p><b>Registros</b>: Listagem e criação de registros</p>
</div>
{% endblock %}

templates/registros/criar_registro.html
{% extends 'base.html' %}

{% block content %}

{% load widget_tweaks %}

<div class="container mt-5">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <form enctype="multipart/form-data" method="post" class="bg-light p-4 rounded shadow-sm needs-validation" novalidate>
                {% csrf_token %}
                <h1 class="text-center mb-4">Criar Registro</h1>

                <!-- Tarefa associada -->
                <div class="mb-3">
                    <label for="id_tarefa" class="form-label">Tarefa</label>
                    {{ form.tarefa|add_class:"form-control" }}
                    <div class="invalid-feedback">
                        Por favor, selecione a tarefa.
                    </div>
                </div>

                <!-- Horas trabalhadas -->
                <div class="mb-3">
                    <label for="id_horas_trabalhadas" class="form-label">Horas Trabalhadas</label>
                    {{ form.horas_trabalhadas|add_class:"form-control" }}
                    <div class="invalid-feedback">
                        Por favor, insira a quantidade de horas trabalhadas. Ex: 1,2...
                    </div>
                </div>

                <!-- Descrição do trabalho -->
                <div class="mb-3">
                    <label for="id_descricao" class="form-label">Descrição do Trabalho</label>
                    {{ form.descricao|add_class:"form-control" }}
                    <div class="invalid-feedback">
                        Por favor, insira uma descrição para o registro. Ex: atualização de dependências dev
                    </div>
                </div>

                <button type="submit" class="btn btn-primary w-100">Criar</button>
            </form>
        </div>
    </div>
</div>

{% load static %}
<script src="{% static 'js/criar_registro.js' %}"></script>

{% endblock %}

templates/registros/lista_registros.html
{% extends 'base.html' %}

{% block title %}Registros{% endblock %}

{% block content %}

<div class="container mt-4">
    <h2 class="mb-4">Registros de Tempo</h2>

    <form method="get" class="mb-4">
        <div class="row">
            <div class="col-md-3 mb-2">
                <div class="input-group">
                    <span class="input-group-text text-bg-dark">Usuário</span>
                    <input type="text" class="form-control" name="usuario" placeholder="Usuário" value="{{ request.GET.usuario }}">
                </div>
            </div>
            <div class="col-md-3 mb-2">
                <div class="input-group">
                    <span class="input-group-text text-bg-dark">Tarefa</span>
                    <input type="text" class="form-control" name="tarefa" placeholder="Tarefa" value="{{ request.GET.tarefa }}">
                </div>
            </div>
            <div class="col-md-3 mb-2">
                <div class="input-group">
                    <span class="input-group-text text-bg-dark">Data</span>
                    <input type="date" class="form-control" name="data" value="{{ request.GET.data }}">
                </div>
            </div>
            <div class="col-md-3 mb-2">
                <div class="input-group">
                    <span class="input-group-text text-bg-dark">Horas</span>
                    <input type="number" class="form-control" name="horas_trabalhadas" placeholder="Horas Trabalhadas" value="{{ request.GET.horas_trabalhadas }}">
                </div>
            </div>
        </div>
        <button type="submit" class="btn btn-primary mt-2">Filtrar</button>
        <a href="{% url 'lista_registros' %}" class="btn btn-secondary mt-2">Limpar filtros</a>
    </form>

    <a href="{% url 'criar_registro' %}" class="btn btn-primary mb-3">Criar Novo Registro</a>

    <table class="table table-striped table-hover mt-3">
        <thead class="table-dark">
            <tr>
                <th>Tarefa</th>
                <th>Data de Registro</th>
                <th>Horas Trabalhadas</th>
                <th>Descrição</th>
            </tr>
        </thead>
        <tbody>
            {% for registro in registros %}
            <tr>
                <td>{{ registro.tarefa }}</td>
                <td>{{ registro.data_registro|date:"d/m/Y" }}</td>
                <td>{{ registro.horas_trabalhadas }} hora(s)</td>
                <td>{{ registro.descricao }}</td>
            </tr>
            {% endfor %}
        </tbody>
    </table>

        <!-- Paginação -->
        {% if is_paginated %}
        <nav aria-label="Page navigation">
            <ul class="pagination justify-content-center">
                {% if page_obj.has_previous %}
                <li class="page-item">
                    <a class="page-link" href="?{% for key, value in request.GET.items %}{% if key != 'page' %}{{ key }}={{ value }}&{% endif %}{% endfor %}page={{ page_obj.previous_page_number }}" aria-label="Anterior">
                        <span aria-hidden="true">&laquo;</span>
                    </a>
                </li>
                {% else %}
                <li class="page-item disabled">
                    <span class="page-link">&laquo;</span>
                </li>
                {% endif %}
    
                {% for num in paginator.page_range %}
                {% if page_obj.number == num %}
                <li class="page-item active">
                    <span class="page-link">{{ num }}</span>
                </li>
                {% elif num > page_obj.number|add:'-3' and num < page_obj.number|add:'3' %}
                <li class="page-item">
                    <a class="page-link" href="?{% for key, value in request.GET.items %}{% if key != 'page' %}{{ key }}={{ value }}&{% endif %}{% endfor %}page={{ num }}">{{ num }}</a>
                </li>
                {% endif %}
                {% endfor %}
    
                {% if page_obj.has_next %}
                <li class="page-item">
                    <a class="page-link" href="?{% for key, value in request.GET.items %}{% if key != 'page' %}{{ key }}={{ value }}&{% endif %}{% endfor %}page={{ page_obj.next_page_number }}" aria-label="Próximo">
                        <span aria-hidden="true">&raquo;</span>
                    </a>
                </li>
                {% else %}
                <li class="page-item disabled">
                    <span class="page-link">&raquo;</span>
                </li>
                {% endif %}
            </ul>
        </nav>
        {% endif %}
</div>

{% endblock %}

templates/tarefas/criar_tarefa.html
{% extends 'base.html' %}


{% block content %}

{% load widget_tweaks %}

<div class="container mt-5">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <form enctype="multipart/form-data" method="post" class="bg-light p-4 rounded shadow-sm needs-validation" novalidate>
                {% csrf_token %}
                <h1 class="text-center mb-4">Criar Tarefa</h1>
                
                <!-- Usuário responsável -->
                <div class="mb-3">
                    <label for="id_usuario_responsavel" class="form-label">Usuário Responsável</label>
                    {{ form.usuario_responsavel|add_class:"form-control" }}
                    <div class="invalid-feedback">
                        Por favor, selecione o usuário responsável.
                    </div>
                </div>

                <!-- Descrição -->
                <div class="mb-3">
                    <label for="id_descricao" class="form-label">Descrição da Tarefa</label>
                    {{ form.descricao|add_class:"form-control" }}
                    <div class="invalid-feedback">
                        A descrição da tarefa é obrigatória. Ex: Atualizar dependências
                    </div>
                </div>

                <button type="submit" class="btn btn-primary w-100">Criar</button>
            </form>
        </div>
    </div>
</div>

{% load static %}
<script src="{% static 'js/criar_tarefa.js' %}"></script>

{% endblock %}

templates/tarefas/lista_tarefas.html
{% extends 'base.html' %}

{% block title %}Tarefas{% endblock %}

{% block content %}

<div class="container mt-4">
    <h2 class="mb-4">Lista de Tarefas</h2>
    
    <a href="{% url 'criar_tarefa' %}" class="btn btn-primary mb-3">Criar Nova Tarefa</a>

    <table class="table table-striped table-hover mt-3">
        <thead class="table-dark">
            <tr>
                <th>Usuário Responsável</th>
                <th>Descrição</th>
                <th>Data de Criação</th>
            </tr>
        </thead>
        <tbody>
            {% for tarefa in tarefas %}
            <tr>
                <td>{{ tarefa.usuario_responsavel }}</td>
                <td>{{ tarefa.descricao }}</td>
                <td>{{ tarefa.data_criacao|date:"d/m/Y" }}</td>
            </tr>
            {% endfor %}
        </tbody>
    </table>

        <!-- Paginação -->
        {% if is_paginated %}
        <nav aria-label="Page navigation">
            <ul class="pagination justify-content-center">
                {% if page_obj.has_previous %}
                <li class="page-item">
                    <a class="page-link" href="?{% for key, value in request.GET.items %}{% if key != 'page' %}{{ key }}={{ value }}&{% endif %}{% endfor %}page={{ page_obj.previous_page_number }}" aria-label="Anterior">
                        <span aria-hidden="true">&laquo;</span>
                    </a>
                </li>
                {% else %}
                <li class="page-item disabled">
                    <span class="page-link">&laquo;</span>
                </li>
                {% endif %}
    
                {% for num in paginator.page_range %}
                {% if page_obj.number == num %}
                <li class="page-item active">
                    <span class="page-link">{{ num }}</span>
                </li>
                {% elif num > page_obj.number|add:'-3' and num < page_obj.number|add:'3' %}
                <li class="page-item">
                    <a class="page-link" href="?{% for key, value in request.GET.items %}{% if key != 'page' %}{{ key }}={{ value }}&{% endif %}{% endfor %}page={{ num }}">{{ num }}</a>
                </li>
                {% endif %}
                {% endfor %}
    
                {% if page_obj.has_next %}
                <li class="page-item">
                    <a class="page-link" href="?{% for key, value in request.GET.items %}{% if key != 'page' %}{{ key }}={{ value }}&{% endif %}{% endfor %}page={{ page_obj.next_page_number }}" aria-label="Próximo">
                        <span aria-hidden="true">&raquo;</span>
                    </a>
                </li>
                {% else %}
                <li class="page-item disabled">
                    <span class="page-link">&raquo;</span>
                </li>
                {% endif %}
            </ul>
        </nav>
        {% endif %}
</div>


{% endblock %}